Allow document from other server, add allow list for document rule
w3c/specberus pull request #1179
Opened 2021-03-16 06:37 UTC by jennyliang220

Closes #1168 , resolve #1155

2021-03-19 05:36 UTC, deniak requested changes

2021-03-19 05:36 UTC, deniak commented on lib/rules/links/linkchecker.js
> +    new RegExp('^https://www.w3.org/scripts/TR/'),
We can allow any scripts under `/scripts/`. We do have control over that folder.
```suggestion
    new RegExp('^https://www.w3.org/scripts/'),
```

2021-03-19 05:36 UTC, deniak commented on lib/rules.json
> +                    "compoundFilesLocation": "If the document is compound (i.e., if it consists of more than one file), all the files <span class=\"rfc2119\">must</span> be under a directory /TR/YYYY
```suggestion
                    "compoundFilesLocation": "If the document is compound (i.e., if it consists of more than one file), all the files <span class=\"rfc2119\">must</span> be under a directory /TR/YYYY/@{param1}-shortname-YYYYMMDD/. Exceptions are resources under these paths:<ol><li>https://www.w3.org/StyleSheets/TR/</li><li>https://www.w3.org/scripts/</li></ol>",
```

2021-03-19 05:36 UTC, deniak commented on lib/rules/links/linkchecker.js
> +        await browser.close();
As you mentioned in our last call, you can move the launch of puppeteer after that `if`

2021-03-19 07:30 UTC, deniak approved these changes

2021-03-19 07:30 UTC, merged

2021-03-22 01:27 UTC, Nuckijfuta reviewed
Revert