Change document for REC
w3c/specberus pull request #1269
Opened 2021-06-03 08:26 UTC by jennyliang220

resolves #1246

2021-06-03 08:46 UTC, jennyliang220 commented
Hi @plehegar , see previews at attachment: [document-preview.zip](https://github.com/w3c/specberus/files/6590183/document-preview.zip)

2021-06-03 13:41 UTC, plehegar approved these changes

2021-06-03 13:41 UTC, plehegar commented
LGTM. thank you @jennyliang220

2021-06-04 05:39 UTC, deniak requested changes
The list for the section 6 (Change "status of this document" section) doesn't seem right.
6.1, 6.2, etc should be in a sublist like in section 3.

Also, `/doc/rules/?profile=REC-OBSOLETE` mentions "For an example, see the diff between the REC and the Obsoleted document of High Resolution Time Level 1", but hr-time-1 is a superseded REC.
<img width="1173" alt="Screen Shot 2021-06-04 at 09 30 21" src="https://user-images.githubusercontent.com/1696128/120751259-c7636900-c518-11eb-9b5e-519ad964dd55.png">

2021-06-04 05:39 UTC, deniak commented on lib/rules.json
> +                        "name": "6. Change \"status of this document\" section",
```suggestion
                        "name": "6. Change the \"Status of this Document\" section",
```

2021-06-04 05:39 UTC, deniak commented on lib/rules.json
> +                        "name": "2. Use corresponding stylesheet",
```suggestion
                        "name": "2. Use the corresponding stylesheet",
```

2021-06-04 05:39 UTC, deniak commented on lib/rules.json
> +                        "name": "4. Set This version link",
```suggestion
                        "name": "4. Set the \"This version\" link",
```

2021-06-04 05:39 UTC, deniak commented on lib/rules.json
> +                        "name": "5. Set Previous version link",
```suggestion
                        "name": "5. Set the \"Previous version\" link",
```

2021-06-04 05:39 UTC, deniak commented on lib/rules.json
> +                        "name": "6. Change \"status of this document\" section",
```suggestion
                        "name": "6. Change the \"Status of this Document\" section",
```

2021-06-04 05:39 UTC, deniak commented on lib/rules.json
> +                "name": "2. Use corresponding stylesheet",
```suggestion
                "name": "2. Use the corresponding stylesheet",
```

2021-06-04 05:39 UTC, deniak commented on lib/rules.json
> +                    "stylesheet":"For the W3C style sheet, use the @{param1} version of the W3C style sheet in use in the REC (old, or 2016). So, it's one of:<ol><li>https://www.w3.org/StyleSheets/TR
```suggestion
                    "stylesheet":"For the W3C stylesheet, use the @{param1} version of the W3C stylesheet in use in the REC (old, or 2016). So, it's one of:<ol><li>https://www.w3.org/StyleSheets/TR/W3C-@{param1}.css</li><li>https://www.w3.org/StyleSheets/TR/2016/W3C-@{param1}.css</li><li>or reuse the (some?) content from https://www.w3.org/TR/html50/superseded.css as needed</li></ol>"
```

2021-06-04 05:39 UTC, deniak commented on lib/rules.json
> +                "name": "4. Set This version link",
```suggestion
                "name": "4. Set the \"This version\" link",
```

2021-06-04 05:39 UTC, deniak commented on lib/rules.json
> +                "name": "5. Set Previous version link",
```suggestion
                "name": "5. Set the \"Previous version\" link",
```

2021-06-04 05:39 UTC, deniak commented on lib/rules.json
> +                "name": "6. Change \"status of this document\" section",
```suggestion
                "name": "6. Change the \"status of this document\" section",
```

2021-06-10 09:56 UTC, deniak approved these changes

2021-06-10 09:56 UTC, merged