fix(rules/headers/mailing-list): drop mailing list in header rule
w3c/specberus pull request #1309
Opened 2021-06-30 07:05 UTC by marcoscaceres

closes #1308

2021-07-02 09:23 UTC, jennyliang220 approved these changes
Approved after a few minor changes.

2021-07-06 04:44 UTC, deniak requested changes
@jennyliang220 since you are renaming the rule, can you also rename and rework the test files `sotd/ml-*` to test the following cases:
* https://github.com/w3/foo/issues/
* https://github.com/w3/foo/labels/
* missing repository

2021-07-06 04:44 UTC, deniak commented on test/rules.js
> +                warnings: [],
```suggestion
```

2021-07-08 05:49 UTC, deniak approved these changes

2021-07-08 05:50 UTC, merged