Add check for current charter.
w3c/specberus pull request #1326
Opened 2021-07-12 07:11 UTC by jennyliang220

resolves #782

2021-07-13 09:07 UTC, deniak requested changes
`lib/rules/sotd/charter-disclosure.js` should probably be renamed to `lib/rules/sotd/charter-disclosure.js` as the "disclosure" part is not checked for documents other than IG Notes

2021-07-13 09:07 UTC, deniak commented on lib/validator.js
> +    [this.patentPolicy] = patentPolicy;
If there's a joint publication, we should check that all the deliverers are operating under the same patent policy.
With the current code, there will be no error if that's not the case and only the first PP will be returned.

2021-07-14 03:23 UTC, jennyliang220 commented on lib/validator.js
> +        deliverers.forEach((deliverer) => {
This was not configured in prettier before, the [default config is to have the parentheses](https://prettier.io/docs/en/options.html#arrow-function-parentheses). So the parentheses are necessary. I don't have a preference, will add  the config to the project.

2021-07-14 04:56 UTC, jennyliang220 commented
> `lib/rules/sotd/charter-disclosure.js` should probably be renamed to `lib/rules/sotd/charter-disclosure.js` as the "disclosure" part is not checked for documents other than IG Notes

Hi @deniak , is `lib/rules/sotd/charter.js` what you meant?

2021-07-14 05:33 UTC, deniak commented
> > `lib/rules/sotd/charter-disclosure.js` should probably be renamed to `lib/rules/sotd/charter-disclosure.js` as the "disclosure" part is not checked for documents other than IG Notes
> 
> Hi @deniak , is `lib/rules/sotd/charter.js` what you meant?

Yes, that's more generic.

2021-07-15 12:53 UTC, deniak commented on lib/rules/sotd/pp.js
> +    if (!patentPolicies[0]) console.log('\n\n no pp!');
```suggestion
```

2021-07-15 13:01 UTC, deniak requested changes

2021-07-15 13:01 UTC, deniak commented on lib/validator.js
> +    chartersData.every(charterData =>
you are mistaking `every` with `forEach`. [`every`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every) should be use to test all elements of the array.
```suggestion
    chartersData.forEach(charterData =>
```

2021-07-21 05:58 UTC, deniak requested changes

2021-07-21 05:58 UTC, deniak commented on lib/l10n-en_GB.js
> +        'This document is published by multiple groups using different versions of Patent Policy. See requirement details at <a href="https://github.com/w3c/specberus/issues/1319#issuecomment-8786190
I don't think we should link to a comment which can be edited in the future.

```suggestion
        'This document is published by multiple groups operating under different versions of the Patent Policy. A document should be published under one and only one Patent Policy, to which all participants in contributing groups have agreed.',
```

2021-07-21 05:58 UTC, deniak commented on lib/l10n-en_GB.js
> +        'The Working Group delivering the document operates under the patent policy "${pp_charter}", but the check is against "${pp_config}". Please change the UI or query parameter to match the char
```suggestion
        'The Working Group delivering the document operates under the patent policy "${pp_charter}", but the check is against "${pp_config}". Please select the right patent policy to match the charter\'s version.',
```

2021-07-21 05:58 UTC, deniak commented on lib/l10n-en_GB.js
> +        'Unable to find the group id (in data-deliverer for Note-Track document, and in Status of This Document for REC-Track document).',
```suggestion
        'Unable to find the group(s) ID(s) (in the <code>data-deliverer</code> attribute for Note-Track documents, and in the "Status of This Document" for REC-Track documents).',
```

2021-07-21 05:58 UTC, deniak commented on lib/validator.js
> +    chartersData.every(charterData => charters.push(charterData.uri));
```suggestion
    chartersData.forEach(charterData => charters.push(charterData.uri));
```

2021-07-21 05:58 UTC, deniak commented on lib/validator.js
> +            // Skip finding charter for TAG group.
```suggestion
            // Skip finding charter for the TAG which doesn't have any charter
```

2021-07-21 05:58 UTC, deniak commented on lib/validator.js
> +        // Find the current charter, and corresponding patentPolicy.
The comment seems inaccurate as we aren't dealing with any patent policy

2021-07-26 08:19 UTC, deniak approved these changes

2021-07-26 08:19 UTC, merged