Improve copyright rule
w3c/specberus pull request #1330
Opened 2021-07-20 09:45 UTC by jennyliang220

Making sure the copyright mentioned in the document is consistant with the Charter.
resolves #1166 

Also split the document for copyright:
![6081626774061_ pic_hd](https://user-images.githubusercontent.com/8498677/126301157-b6e76541-ea23-42bd-baaf-da40b87b3668.jpg)

2021-07-20 09:48 UTC, jennyliang220 commented
Failed lint because this PR is using the rule changed in https://github.com/w3c/specberus/pull/1326. After merging #1326, the check would be good.

2021-07-21 06:48 UTC, deniak requested changes

2021-07-21 06:48 UTC, deniak commented on lib/l10n-en_GB.js
> +        "Could not get the document license from the API. Please make sure this group has a current charter, and it's mentioning at least one document license.",
```suggestion
        "Could not get the document license from the API. Please make sure this group has a current charter associated with at least one document license.",
```

2021-07-21 06:48 UTC, deniak commented on lib/l10n-en_GB.js
> +        "This document is published by multiple groups, but these groups doesn't agree on the same document license. Please ask the team contact for help.",
```suggestion
        "This document is published by multiple groups, but these groups don't use the same document license. Please ask the team contact for help.",
```

2021-07-21 06:48 UTC, deniak commented on lib/rules/headers/copyright.js
> + * 5.For "copyright-documents", the url is https://www.w3.org/Consortium/Legal/copyright-documents. The name in the API is "W3C Document License", but the document would use text "document use".
```suggestion
 * 5. For "copyright-documents", the url is https://www.w3.org/Consortium/Legal/copyright-documents. The name in the API is "W3C Document License", but the document would use text "document use".
```

2021-07-21 06:48 UTC, deniak commented on lib/rules/headers/copyright.js
> +        });
```suggestion
        const licenses = [...charterData.map((c => c['doc-licenses'].map(l => l.uri)))]; // creates an array of license URIs per group -> array of arrays
        const allowedLicenses = licenses.reduce((a, b) => a.filter(c => b.includes(c))); // find the intersection of all arrays
```

2021-07-21 06:48 UTC, deniak commented on lib/rules/headers/copyright.js
> +            sr.error(self, 'no-license-found');
```suggestion
            sr.error(self, (isJoinPublication) ? 'no-license-found-joint' : 'no-license-found');
```

2021-07-21 06:48 UTC, deniak commented on lib/rules/headers/copyright.js
> +        if (!regResult) sr.error(self, 'no-match', { rex });
Shouldn't we stop the rule if there's no match?

2021-07-26 13:02 UTC, deniak commented on lib/rules/headers/copyright.js
> +            sr.error(self, 'no-license-found');
it's actually breaking the l10n test

2021-07-26 13:30 UTC, deniak approved these changes

2021-07-26 13:30 UTC, merged