Add stability check for registry track
w3c/specberus pull request #1410
Opened 2021-11-05 08:50 UTC by jennyliang220

2021-11-05 09:08 UTC, deniak requested changes
stability.js is not checking the additional sentence needed in CRY and CRYD.

2021-11-08 01:21 UTC, jennyliang220 commented
> stability.js is not checking the additional sentence needed in CRY and CRYD.

The implementation of this feature will be in a new PR, after https://github.com/w3c/tr-design/pull/271 is addressed.

2021-11-08 04:50 UTC, deniak requested changes

2021-11-08 04:50 UTC, deniak commented on lib/rules/sotd/draft-stability.js
> +    if (
I don't know why this hasn't been removed earlier but if a check doesn't do anything for specific profiles, then the rule ought to be removed from the profile itself exactly like how you are doing it for CRY.

2021-11-08 04:50 UTC, deniak commented on lib/profiles/TR/CRY.js
> +    longStatus: 'Candidate Registry',
I don't understand how the tests passed with the previous longStatus. Are we even testing this?

2021-11-09 10:34 UTC, deniak approved these changes

2021-11-09 10:34 UTC, merged