Manual check
w3c/specberus pull request #1436
Opened 2021-11-20 00:15 UTC by jennyliang220

2021-11-23 05:16 UTC, deniak requested changes
The profiles are quite messy. Please make some clean up so it's easier to follow what each profile actually checks.

2021-11-23 05:16 UTC, deniak commented on lib/profiles/TR/CRD.js
> +rules = base.insertAfter(rules, 'sotd.supersedable', [
This is quite messy.
* TR.js has `draft-stability`
* CR.js extends TR.js but removes `draft-stability` from the rules list

and now, CRD.js extends CR.js but re-adds `draft-stability`. This requires some clean up.

2021-11-23 05:16 UTC, deniak commented on lib/profiles/TR/CRYD.js
> +rules = base.insertAfter(rules, 'sotd.supersedable', [
Same comment as above

2021-11-23 05:16 UTC, deniak commented on lib/profiles/TR/DNOTE.js
> +const rules = base.insertAfter(note.rules, 'sotd.supersedable', [
Same comment as above

2021-11-23 05:16 UTC, deniak commented on lib/profiles/TR/DRY.js
> +rules = base.insertAfter(rules, 'sotd.supersedable', [
Same comment as above

2021-11-25 07:18 UTC, jennyliang220 commented
Will address the comments in another PR. See issue https://github.com/w3c/specberus/issues/1442

2021-11-25 07:29 UTC, merged