Split profiles into track folders
w3c/specberus pull request #1452
Opened 2021-12-03 12:51 UTC by jennyliang220

2021-12-07 12:00 UTC, deniak requested changes

2021-12-08 07:44 UTC, jennyliang220 commented on lib/profiles/SUBM/MEM-SUBM.js
> +const profileUtil = require('../profileUtil');
You're right. This PR is just re-organizing the rules and profiles, will address in another issue: https://github.com/w3c/specberus/issues/1469

2021-12-08 07:46 UTC, jennyliang220 commented on lib/profiles/TR/Registry/registry-base.js
> +    require('../../../rules/sotd/usage'),
Yes. And I'm thinking if we could let documentation use **extend** as well. So that we don't have to add for each profile.

2021-12-08 10:05 UTC, deniak commented on lib/profiles/TR/Registry/registry-base.js
> +    require('../../../rules/sotd/usage'),
that would be nice!

2021-12-08 10:07 UTC, deniak approved these changes

2021-12-08 10:07 UTC, merged