Add test for WD and FPWD regarding shortname
w3c/specberus pull request #1648
Opened 2022-09-29 04:52 UTC by jennyliang220

- Remove unused variable, [resolves](https://github.com/w3c/specberus/issues/1646)
- Add check for FPWD and WD, FPWD should use a unique shortname while WD uses an existing one, [resolves](https://github.com/w3c/specberus/issues/1644)
- add test to check shortname [TBD]

2022-09-29 06:05 UTC, deniak requested changes

2022-09-29 06:05 UTC, deniak commented on lib/l10n-en_GB.js
> +        'The ${status} should use an unique shortname".',
```suggestion
        'The ${status} should use an unique shortname.',
```

2022-09-29 06:05 UTC, deniak commented on lib/l10n-en_GB.js
> +        'The ${status} should use an existing shortname".',
```suggestion
        'The ${status} should use an existing shortname.',
```

2022-10-10 10:08 UTC, jennyliang220 commented
Pubrules requires the shortname mentioned in **This Version** and **Supersades this Recommendation**, as well as **Obsoletes this Recommendation** to be the same. 

https://github.com/w3c/specberus/blob/bf01c4463b297c4a691a622b663da784b9321b2a/lib/l10n-en_GB.js#L95-L96

Some [test errors](https://github.com/w3c/specberus/actions/runs/3218424407/jobs/5262581561#step:6:2857) in this PR are related.

In case of FPWD, it's intended to replace the Rec document, so it should use a different shortname, @deniak WDYT?

<img width="586" alt="Screen Shot 2022-10-10 at 5 13 13 PM" src="https://user-images.githubusercontent.com/8498677/194842289-1114e177-e4a2-4b89-9495-f98668444359.png">

<img width="703" alt="Screen Shot 2022-10-10 at 5 08 53 PM" src="https://user-images.githubusercontent.com/8498677/194842330-7518d9d8-80ca-4839-9be2-4cbaddc2b787.png">

2022-10-10 10:14 UTC, deniak commented
> In case of FPWD, it's intended to replace the Rec document, so it should use a different shortname, @deniak WDYT?

Yes, shortnames should be different. However, I don't think I've ever seen that use case (FPWD +  Supersedes|Obsoletes this Recommendation). Especially now with the new process where groups have a way to update an existing Recommendation without too much hassle.

2022-10-11 04:21 UTC, jennyliang220 commented
> shortnames should be different. However, I don't think I've ever seen that use case (FPWD + Supersedes|Obsoletes this Recommendation).

Searching recent 700 documents back to 2014, there's no **Supersades this Recommendation** nor **Obsoletes this Recommendation** mentioned in the headers. Maybe we could drop the test, as well as the rule.

2022-10-14 11:05 UTC, deniak requested changes

2022-10-14 11:05 UTC, deniak commented on lib/validator.js
> +    if (!shortname) return false;
```suggestion
    if (!shortname) return;
```

2022-10-17 02:57 UTC, jennyliang220 commented on lib/rules/headers/w3c-state.js
> +export async function check(sr, done) {
```suggestion
export function check(sr, done) {
```

2022-10-17 06:09 UTC, deniak commented on lib/rules/headers/w3c-state.js
> +export async function check(sr, done) {
reverted in https://github.com/w3c/specberus/pull/1648/commits/0f3d587755b716afb0ec0079a5aeb83a4f30179b

2022-10-27 03:47 UTC, jennyliang220 commented on lib/rules/headers/dl.js
> +        shortname
If shortname in headers not extracted (edge case exists in test), there's no previous version link, `isFP` is true, it'll go into the `if` condition. So `shortname` is necessary.

2022-10-27 07:13 UTC, jennyliang220 commented on lib/rules/headers/dl.js
> +        shortname
// check shortname before send the request in getPreviousVersions()

2022-10-27 07:27 UTC, jennyliang220 commented
separate a new rule `shortname.js` to check shortname existence for REC

2022-11-04 12:05 UTC, deniak requested changes

2022-11-04 12:05 UTC, deniak commented on lib/l10n-en_GB.js
> +        'The ${status} should use an unique shortname.',
The status will always be 'First Public Working Draft' the way it's being used in `shortname.js`. No need to pass an extra parameter.
```suggestion
        'FPWDs must use a new shortname.',
```

2022-11-04 12:05 UTC, deniak commented on lib/rules/headers/shortname.js
> +        });
changes related to the suggestion in `l10-en_GB.js`.
```suggestion
        sr.error(self, 'shortname-existed');
```

2022-11-07 03:09 UTC, jennyliang220 commented on lib/l10n-en_GB.js
> +    'headers.shortname.history-syntax':
Yes, the existence of history link is checked [here in dl.js](https://github.com/w3c/specberus/pull/1648/files/eace9740d9068b45d3fe2ec77b1a38dd0803fa85#diff-cf098e75516357312f91fb778a977b2fb8e6473b3130ad33efb1ae48c36cf085R65), and the format is checked in [later in dl.js](https://github.com/w3c/specberus/pull/1648/files#diff-cf098e75516357312f91fb778a977b2fb8e6473b3130ad33efb1ae48c36cf085R134) , I move the shortname check to the new `shortname.js` rule.

2022-11-07 04:36 UTC, deniak commented on lib/l10n-en_GB.js
> +    'headers.shortname.history-syntax':
Indeed!

2022-11-07 06:12 UTC, jennyliang220 commented on lib/rules/headers/shortname.js
> +                    var hasPreviousVersion = !(await sr.isFP());
`Specberus.prototype.isFP` saves the result of the Promise

2022-11-07 10:04 UTC, merged