Process 2020 features
w3c/specberus pull request #954
Opened 2020-08-21 07:38 UTC by jennyliang220

2020-08-31 05:28 UTC, deniak requested changes

2020-08-31 05:28 UTC, deniak commented on lib/profiles/TR/CRD.js
> +exports.name = "CR";
```suggestion
exports.name = "CRD";
```

2020-08-31 05:40 UTC, deniak requested changes
On the UI, if you select the checkbox 'Echidna-ready', the profile CRD becomes disabled. 
`public/js/specberus.js` should be updated accordingly.

2020-08-31 06:27 UTC, deniak requested changes

2020-08-31 06:27 UTC, deniak commented on lib/rules.json
> +                            "crIntro": "W3C Candidate Recommendation Snapshot <span class=\"rfc2119\">must</span> include 2 paragraphs in \"Status Of This Document\": <pre xml:space=\"preserve\" styl
The text should include how the paragraphs look like and the source code the editors can copy/paste

```suggestion
                            "crIntro": "It <span class=\"rfc2119\">must</span> include the following two paragraphs in \"Status Of This Document\": <blockquote><p>Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. A Candidate Recommendation Snapshot has received <a href=\"https://www.w3.org/2020/Process-20200915/#dfn-wide-review\">wide review</a> and is intended to gather implementation experience.</p></blockquote><blockquote><p>This document was published by the @@@WG Name@@@ Working Group as a Candidate Recommendation Snapshot.</p></blockquote><div class=\"source\"> <span style=\"font-style: italic\">Include this source code</span>:<br><code>&lt;p&gt;Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. A Candidate Recommendation Snapshot has received &lt;a href\"https://www.w3.org/2020/Process-20200915/#dfn-wide-review\"&gt;wide review&lt;/a&gt; and is intended to gather implementation experience.&lt;/p&gt;<br>&lt;p&gt;This document was published by the @@@WG Name@@@ Working Group as a Candidate Recommendation Snapshot.&lt;/p&gt;</code></div>",
```

2020-08-31 06:27 UTC, deniak commented on lib/rules.json
> +                            "h3CrType": true,
This should be moved *after* "dateTitleH2" so it keeps the same order as on the document.

2020-08-31 06:27 UTC, deniak commented on lib/rules.json
> +                    "h3CrType": "The CR document's head <span class=\"rfc2119\">must</span> have a <code>h3</code> element. For Candidate Recommendation Draft, it's <pre xml:space=\"preserve\">&lt;h3
I suggest you have the instruction for CR snapshot here but overwrite it for the profile CRD to be more specific on what is expected for both profiles.

2020-08-31 06:27 UTC, deniak commented on lib/rules.json
> +                                "CR"
```suggestion
                                "CRD"
```

2020-08-31 06:27 UTC, deniak commented on lib/rules/sotd/cr-intro.js
> +exports.check = function (sr, done) {
You are checking 2 paragraphs in that rule but the first one should be checked in 'lib/sotd/stability.js'. It's just a variation of that rule.

2020-08-31 07:00 UTC, deniak requested changes

2020-08-31 07:00 UTC, deniak commented on lib/rules/sotd/process-document.js
> +        from:         new Date('2020-09-14')
In our case, we don't need to use the transition function as we don't have a transition period to switch processes.
The rule can be simplified (pseudo-code):
```
if (docDate < '2020-09-15') {
    proc = "1 March 2019"
    deprecatedUri = 'https://www.w3.org/2019/Process-20190301/'
} else {
    proc = "15 September 2020"
    procUri = "https://www.w3.org/2020/Process-20200915/"
}
```

No need to worry about deprecated process documents as we simply don't allow them.

2020-09-01 09:59 UTC, deniak commented on lib/rules/sotd/process-document.js
> +        from:         new Date('2020-09-14')
addressed in https://github.com/w3c/specberus/pull/954/commits/002ba22e7f19635237dbac24f02d2e41bb9206ba

2020-09-01 11:51 UTC, deniak requested changes

2020-09-01 11:51 UTC, deniak commented on lib/rules/headers/dl.js
> +        sr.error(self, "implelink-not-found");
Implementation reports are required only for CR, PR and REC. This would trigger an error for the other types of document

2020-09-03 06:00 UTC, deniak requested changes

2020-09-03 06:00 UTC, deniak commented on lib/rules/sotd/publish.js
> +    var text = 'This document was published by the (.)+ Working Group as a Candidate Recommendation ' + crType + '.';
The regex isn't exactly right.
A document could be a joint publication between 2 WGs or published by the "Technical Architecture Group". See https://github.com/w3c/specberus/blob/main/lib/rules/sotd/pp.js#L63

```suggestion
    var text = 'This document was (?:produced|published) by the (.+? Working Group|Technical Architecture Group)( and the (.+? Working Group|Technical Architecture Group))? as a Candidate Recommendation ' + crType + '.';
```

2020-09-03 06:24 UTC, deniak commented on lib/rules/sotd/publish.js
> +    name: 'sotd.publish'
That rule should now also be applied to RECs with update to the regex below

2020-09-03 06:36 UTC, deniak requested changes

2020-09-03 06:36 UTC, deniak commented on lib/l10n-en_GB.js
> +,   "sotd.rec-comment-end.not-found": "This W3C Recommendation has subtantive changes or new features, cannot find comment end date no earlier than ${minimumEndDate}."
Format the date in a human readable format. Currently, that's the message that is being generated:
"This W3C Recommendation has subtantive changes or new features, cannot find comment end date no earlier than Sat Nov 14 2020 00:00:00 GMT+0000 (Coordinated Universal Time)."

Only "Nov 14 2020" is be enough

2020-09-04 03:12 UTC, deniak requested changes

2020-09-04 03:12 UTC, deniak commented on lib/rules/headers/dl.js
> +    var needImple = ["CR", "PR", "REC"].indexOf(sr.config.status) !== -1;
```suggestion
    var needImple = ["CR", "CRD", "PR", "REC"].indexOf(sr.config.status) !== -1;
```

2020-09-04 05:06 UTC, deniak requested changes

2020-09-04 11:35 UTC, deniak requested changes

2020-09-04 11:35 UTC, deniak commented on lib/rules/metadata/profile.js
> +                meta.implementationReport = dts.Implementation.dd.querySelector("a").getAttribute('href');
```suggestion
                meta.implementationReport = dts.Implementation.dd.querySelector("a").href;
```

2020-09-07 04:49 UTC, jennyliang220 commented on lib/rules/sotd/publish.js
> +                        PROPOSED_TEXT = /proposed addition(s)/;
```suggestion
                        PROPOSED_TEXT = /proposed addition(s)?/;
```

2020-09-07 04:54 UTC, jennyliang220 commented on lib/validator.js
> -            dates.list.push(d);
dates.list is still being used.

https://github.com/w3c/specberus/blob/b604251e2eb2303227e30c1dce282da2aa410643/lib/rules/sotd/cr-end.js#L28-L30

2020-09-07 09:06 UTC, deniak approved these changes
Approved but pending more tests.

2020-09-09 11:17 UTC, deniak approved these changes

2020-09-09 13:09 UTC, deniak requested changes

2020-09-09 13:09 UTC, deniak commented on lib/rules/headers/mailing-list.js
>  ,   section: 'document-status'
```suggestion
,   section: 'front-matter'
```

2020-09-09 14:09 UTC, deniak requested changes

2020-09-09 14:09 UTC, deniak commented on lib/rules.json
> +                            "stability": "It <span class=\"rfc2119\">must</span> set expectations about the (in)stability of the document. The <span class=\"rfc2119\">recommended</span> text is: <blo
```suggestion
                            "stability": "It <span class=\"rfc2119\">must</span> set expectations about the (in)stability of the document. The <span class=\"rfc2119\">recommended</span> text is: <blockquote class=\"boilerplate\"> <p>Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. A Candidate Recommendation Snapshot has received <a href=\"https://www.w3.org/2020/Process/20200915/#dfn-wide-review\">wide review</a> and is intended to gather implementation experience.</p> </blockquote> <div class=\"source\"> <span style=\"font-style: italic\">Include this source code</span>:<br><code>&lt;p&gt;Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. A Candidate Recommendation Snapshot has received &lt;a href\"https://www.w3.org/2020/Process/20200915/#dfn-wide-review\"&gt;wide review&lt;/a&gt; and is intended to gather implementation experience.&lt;/p&gt;</code></div>",
```

2020-09-11 06:56 UTC, jennyliang220 commented on lib/rules/sotd/stability.js
> +    ,   INTRO_D = "A Candidate Recommendation Draft integrates changes from the previous Candidate Recommendation that the Working Group intends to include in a subsequent Candidate Recommendation Sn
```suggestion
    ,   INTRO_D = "A Candidate Recommendation Draft is published changes from the previous Candidate Recommendation that the Working Group intends to include in to solicit review of intended changes from the previous Candidate Recommendation Snapshot."
```

Change in accordance with  https://github.com/w3c/tr-design/pull/209/files

2020-09-14 07:18 UTC, deniak approved these changes

2020-09-15 01:06 UTC, merged